### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by JinjaeKim** [ysBach/ysfitsutilpy#3]
$ cd <where you want to download this package>
$ git clone https://github.com/ysBach/ysphotutilpy
$ cd ysphotutilpy
$ python setup.py install

ysphotutilpy >> ysfitsutilpy 이렇게 수정해야 맞는거죠!?

**Comment by ysBach** [comment]
Thanks for the report.
You are absolutely right. 
Will push an update very soon.
